# Generated by Django 4.1.5 on 2023-01-23 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 23, 14, 4, 4, 331521, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 23, 14, 4, 4, 331521, tzinfo=datetime.timezone.utc)),
        ),
    ]
