# Generated by Django 4.1.5 on 2023-01-23 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_alter_comment_added_at_alter_post_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
